name: firenotes
description: Notes App using Firebase & Firestore as Backend

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.5.0+3
  scoped_model: ^1.0.1

  firebase_core: ^0.3.1
  firebase_storage: ^2.1.0
  cloud_firestore: ^0.9.5
  cloud_functions: ^0.1.1
  transparent_image: ^0.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

